"use client"
import { Inter } from "next/font/google";
import "./global.js";
import { Provider } from "react-redux";
import store from "./store/Store.js";
// const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>{children}</Provider>
      </body>
    </html>
  );
}
